#!python
# -*-coding:utf-8-*-
# Reduce high-order element to basic element, the high-order elements always generated by ASPECT
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 'Zhikui Guo, 2021/06/25, GEOMAR
# ===============================================================

import sys
import argparse
import sys
import os
from colored import fg, bg, attr
C_GREEN = fg('green')
C_RED = fg('red')
C_BLUE = fg('blue')
C_DEFAULT = attr('reset')
#===============================================================
from vtk import *
from vtk.util import numpy_support as VN
import meshio 
import numpy as np 

def ERROR(errInfo,end='\n'):
    print('[%sError%s]: %s%s%s'%(C_RED,C_DEFAULT,C_BLUE,errInfo,C_DEFAULT))
    exit(0)
def Status(info,end='\n'):
    print('[%sStatus%s]: %s%s%s'%(C_GREEN,C_DEFAULT,C_BLUE,info,C_DEFAULT),end=end)
def usage(argv):
    basename = argv[0].split('/')
    basename = basename[len(basename)-1]
    description='Reduce high-order element to basic element, the high-order elements always generated by ASPECT'
    num_symbol=int((len(description)+20 - len(basename))/2)
    head='='*num_symbol+basename+'='*num_symbol
    print(head)
    print(description)
    print('Zhikui Guo, 2021/06/25, GEOMAR')
    print('[Example]: '+C_RED + basename+C_BLUE + ' my.vtu'+C_DEFAULT)
    print('='*len(head))
# convert ASPECT 2D vtu mesh to lower order element
def ReduceHighOrderElement2D_to_3D(inputVTKFile,toGmsh=False, to3D=True):
    extension=inputVTKFile.split('.')[-1]
    reader,writer=[],[]
    outputVTKFile='reduced.vtu'
    if(extension=='vtu'):
        reader=vtkXMLUnstructuredGridReader()
        writer=vtkXMLUnstructuredGridWriter()
        outputVTKFile=inputVTKFile.replace('.vtu','_reduce.vtu')
    elif(extension=='vtk'):
        reader=vtkUnstructuredGridReader()
        writer=vtkUnstructuredGridWriter()
        outputVTKFile=inputVTKFile.replace('.vtk','_reduce.vtk')
    else:
        ERROR('Unrecognized vtk file type: %s, the supported format is vtu'%(extension))
    reader.SetFileName(inputVTKFile)
    reader.Update()
    grid=reader.GetOutput()
    # ======= remove not extracted fields ===========
    # point data field
    num_pointDataField=grid.GetPointData().GetNumberOfArrays()
    extractPointFieldNames,rmPointFieldNames=[],[]
    pointFieldNames=['']*num_pointDataField
    numCells=grid.GetNumberOfCells()
    numPoints=grid.GetNumberOfPoints()
    # construct unstructured mesh grid
    VTU = vtkUnstructuredGrid()
    ratio_extrude=10
    if(to3D==True):
        points=grid.GetPoints()
        bounds=points.GetBounds()
        xyz=VN.vtk_to_numpy(points.GetData())
        len_x,len_y,len_z=bounds[3]-bounds[0],bounds[4]-bounds[1],bounds[5]-bounds[2]
        xyz_ex=xyz.copy()
        if(len_z==0):
            print('extrude along z axis')
            dz=(len_x+len_y)/2/ratio_extrude
            xyz_ex[:,2]+=dz
        elif(len_x==0):
            print('extrude along x axis')
            dx=(len_z+len_y)/2/ratio_extrude
            xyz_ex[:,0]+=dx
        elif(len_y==0):
            print('extrude along y axis')
            dy=(len_x+len_z)/2/ratio_extrude
            xyz_ex[:,1]+=dy
        else:
            Error('This is not a simple 2D mesh, because the plane is not parell to any of x,y,z axis: %f, %f, %f'%(len_x,len_y,len_z))
        vtk_points = vtkPoints()
        for i in range(xyz.shape[0]):
            vtk_points.InsertNextPoint(xyz[i,0],xyz[i,1],xyz[i,2])
        for i in range(xyz_ex.shape[0]):
            vtk_points.InsertNextPoint(xyz_ex[i,0],xyz_ex[i,1],xyz_ex[i,2])
        VTU.SetPoints(vtk_points)
        # cells
        vtk_hex = vtkHexahedron()
        vtk_cells = vtkCellArray()
        for i in range(0,numCells):
            cell = grid.GetCell(i)
            cellType=cell.GetCellType()
            nump=cell.GetNumberOfPoints()
            points=cell.GetPoints()
            pointIDs=cell.GetPointIds()
            for j in range(0,4):
                vtk_hex.GetPointIds().SetId(j,pointIDs.GetId(j))
                vtk_hex.GetPointIds().SetId(j+4,pointIDs.GetId(j)+numPoints)
            vtk_cells.InsertNextCell(vtk_hex)
        VTU.SetCells(VTK_HEXAHEDRON, vtk_cells)
    else:
        VTU.SetPoints(grid.GetPoints())
        # cells
        vtk_pixel = vtkQuad()
        vtk_cells = vtkCellArray()
        for i in range(0,numCells):
            cell = grid.GetCell(i)
            cellType=cell.GetCellType()
            nump=cell.GetNumberOfPoints()
            points=cell.GetPoints()
            pointIDs=cell.GetPointIds()
            for j in range(0,4):
                # print(pointIDs.GetId(j))
                vtk_pixel.GetPointIds().SetId(j,pointIDs.GetId(j))
            #     print(points.GetPoint(j)[0],points.GetPoint(j)[1],points.GetPoint(j)[2])
            # print(nump,cellType,VTK_LAGRANGE_QUADRILATERAL)
            vtk_cells.InsertNextCell(vtk_pixel)
        VTU.SetCells(VTK_QUAD, vtk_cells)
    # cell data
    for i in range(0,num_pointDataField):
        pd=VN.vtk_to_numpy(grid.GetPointData().GetArray(i))
        fieldName=grid.GetPointData().GetArrayName(i)
        celldata = vtkFloatArray()
        celldata.SetName(fieldName)
        celldata.SetNumberOfTuples(numCells)
        if(len(pd.shape)==1):
            celldata.SetNumberOfComponents(1)
            for j in range(0,numCells):
                celldata.SetValue( j, pd[j*9+8])
            VTU.GetCellData().AddArray(celldata)
        elif(len(pd.shape)==2):
            celldata.SetNumberOfComponents(3)
            celldata.SetNumberOfValues(numCells*3)
            for j in range(0,numCells):
                celldata.SetTuple3( j,0,0,0)
            VTU.GetCellData().AddArray(celldata)
            
        else:
            print('Unknown field dimension:',pd.shape, '%s it is neither a scalar nor vector'%(fieldName))
            Status('Skip %s field'%(fieldName))
    celldata = vtkFloatArray()
    celldata.SetName('cellID')
    celldata.SetNumberOfTuples(numCells)
    celldata.SetNumberOfComponents(1)
    for j in range(0,numCells):
        celldata.SetValue( j, j)
    VTU.GetCellData().AddArray(celldata)
    # ========= write ===========
    writer.SetFileName(outputVTKFile)
    writer.SetInputData(VTU)
    writer.Write()
    Status('The reduced VTU file are save as: %s'%(outputVTKFile))
    if(toGmsh==True):
        data=meshio.read(outputVTKFile)
        data.point_data={}
        data.cell_data={}
        outputGmshFile=outputVTKFile.replace('.'+extension,'.msh')
        data.write(outputGmshFile,file_format='gmsh22',binary=False)
        Status('The converted gmsh file are save as: %s'%(outputGmshFile))
def writeField_OpenFOAM(caseDir, field, fieldName,timeName='0'):
    if(fieldName!='T'):
        return
    os.system('mkdir -p %s/%s'%(caseDir,timeName))
    fpout=open('%s/%s/%s'%(caseDir,timeName,fieldName),'w')
    class_name='volScalarField'
    if(field.shape[1]>1):
        class_name='volVectorField'
    # head
    fpout.write('FoamFile\n')
    fpout.write('{\n')
    fpout.write('    version     2.0;\n')
    fpout.write('    format      ascii;\n')
    fpout.write('    class       %s;\n'%(class_name))
    fpout.write('    location    "%s";\n'%(timeName))
    fpout.write('    object      %s;\n'%(fieldName))
    fpout.write('}\n')
    # body
    fpout.write('dimensions      [0 0 0 1 0 0 0];\n')
    fpout.write('internalField   nonuniform List<scalar> \n')
    fpout.write('%d\n'%(field.shape[0]))
    fpout.write('(\n')
    if(class_name=='volScalarField'):
        for i in range(0,field.shape[0]):
            fpout.write('%f\n'%(field[i]))
    elif(class_name=='volVectorField'):
        for i in range(0,field.shape[0]):
            fpout.write('( ')
            for j in range(0,field.shape[1]):
                fpout.write('%f '%(field[i][j]))
            fpout.write(')')
    fpout.write(')\n;\n')
    # boundary
    fpout.write('boundaryField\n')
    fpout.write('{\n')
    for bdName, bdType in zip(['left','right','bottom','top','front','back'],['zeroGradient']*6):
        fpout.write('\t%s { type %s; }\n'%(bdName,bdType))
    fpout.write('}\n')
    fpout.close()
def ReduceHighOrderElement2D_to_OpenFOAM(inputVTKFile, caseDir,toGmsh=False, to3D=True):
    extension=inputVTKFile.split('.')[-1]
    reader,writer=[],[]
    outputVTKFile='reduced.vtu'
    if(extension=='vtu'):
        reader=vtkXMLUnstructuredGridReader()
        writer=vtkXMLUnstructuredGridWriter()
        outputVTKFile=inputVTKFile.replace('.vtu','_reduce.vtu')
    elif(extension=='vtk'):
        reader=vtkUnstructuredGridReader()
        writer=vtkUnstructuredGridWriter()
        outputVTKFile=inputVTKFile.replace('.vtk','_reduce.vtk')
    else:
        ERROR('Unrecognized vtk file type: %s, the supported format is vtu'%(extension))
    reader.SetFileName(inputVTKFile)
    reader.Update()
    grid=reader.GetOutput()
    # ======= remove not extracted fields ===========
    # point data field
    num_pointDataField=grid.GetPointData().GetNumberOfArrays()
    extractPointFieldNames,rmPointFieldNames=[],[]
    pointFieldNames=['']*num_pointDataField
    numCells=grid.GetNumberOfCells()
    numPoints=grid.GetNumberOfPoints()
    
    # cell data
    for i in range(0,num_pointDataField):
        pd=VN.vtk_to_numpy(grid.GetPointData().GetArray(i))
        fieldName=grid.GetPointData().GetArrayName(i)
        field=[]
        celldata = vtkFloatArray()
        celldata.SetName(fieldName)
        celldata.SetNumberOfTuples(numCells)
        
        if(len(pd.shape)==1):
            field=np.zeros((numCells,1))
            for j in range(0,numCells):
                field[j]=pd[j*9+8]
        elif(len(pd.shape)==2):
            field=np.zeros((numCells,3))
            for j in range(0,numCells):
                for k in range(0,pd.shape[1]):
                    field[j][k]=pd[j*9+8,k]
        else:
            print('Unknown field dimension:',pd.shape, '%s it is neither a scalar nor vector'%(fieldName))
            Status('Skip %s field'%(fieldName))
        writeField_OpenFOAM(caseDir, field, fieldName, timeName='1')
def getCellType(inputVTKFile):
    extension=inputVTKFile.split('.')[-1]
    reader,writer=[],[]
    outputVTKFile='reduced.vtu'
    if(extension=='vtu'):
        reader=vtkXMLUnstructuredGridReader()
        writer=vtkXMLUnstructuredGridWriter()
        outputVTKFile=inputVTKFile.replace('.vtu','_reduce.vtu')
    elif(extension=='vtk'):
        reader=vtkUnstructuredGridReader()
        writer=vtkUnstructuredGridWriter()
        outputVTKFile=inputVTKFile.replace('.vtk','_reduce.vtk')
    else:
        ERROR('Unrecognized vtk file type: %s, the supported format is vtu'%(extension))
    reader.SetFileName(inputVTKFile)
    reader.Update()
    grid=reader.GetOutput()
    # check cell type
    cellType=grid.GetCell(0).GetCellType()
    return cellType
def main(argv):
    parser = argparse.ArgumentParser()
    # parser.add_argument('-s', '--save', help='save animation',action='store_true')
    parser.add_argument('inputVTUFile',type=str, help='Input VTU file')
    parser.add_argument('-o','--caseDir',type=str, help='output to OpenFOAM case dir',default='')
    args = parser.parse_args()
    inputVTUFile=args.inputVTUFile
    caseDir=args.caseDir
    cellType=getCellType(inputVTUFile)
    if(cellType==VTK_LAGRANGE_QUADRILATERAL):
        if(os.path.exists(caseDir)):
            ReduceHighOrderElement2D_to_OpenFOAM(inputVTUFile,caseDir)
        else:
            ReduceHighOrderElement2D_to_3D(inputVTUFile)
    else:
        Error('The cell type %d is not supported so far'%(cellType))

if __name__ == '__main__':
    sys.exit(main(sys.argv))